version: "3.7"

services:
  redis:
    image: redis
    container_name: tutorial_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redis-commander:
    container_name: tutorial_redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  mongodb:
    image: mongo:latest
    container_name: tutorial_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    container_name: tutorial_backend
    build:
      context: ./
    environment:
      REDIS_URL: redis:6379
      MONGODB_URI: mongodb://mongodb:27017/event_management
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 1000
    ports:
      - 5000:5000
    volumes:
      - ./:/var/app
    depends_on:
      - redis
      - mongodb

  frontend:
    container_name: tutorial_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/var/app
      - /var/app/node_modules
    depends_on:
      - server
    stdin_open: true
    tty: true

volumes:
  mongodb_data: